// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VM_Server.Repositories;

#nullable disable

namespace VM_Server.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VM_Server.Model.Experiences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndDate")
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .HasColumnType("text");

                    b.Property<string>("StartDate")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("vm_experiences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07e0c23d-c4dd-4e27-b2d9-0e74284d7a79"),
                            Company = "DepEd Biñan City Division Information Office",
                            CreatedDateTime = new DateTime(2024, 11, 7, 16, 47, 0, 70, DateTimeKind.Utc).AddTicks(8266),
                            EndDate = "July 2022",
                            RoleName = "Frontend Developer",
                            StartDate = "April 2022"
                        },
                        new
                        {
                            Id = new Guid("ce2affed-4d36-462d-99dc-2479745c0c4a"),
                            Company = "Upwork",
                            CreatedDateTime = new DateTime(2024, 11, 7, 16, 47, 0, 70, DateTimeKind.Utc).AddTicks(8273),
                            EndDate = "January 2023",
                            RoleName = "Freelance Web Developer",
                            StartDate = "September 2020"
                        },
                        new
                        {
                            Id = new Guid("cadb233f-013c-4a65-82f5-d1865c640595"),
                            Company = "Upwork",
                            CreatedDateTime = new DateTime(2024, 11, 7, 16, 47, 0, 70, DateTimeKind.Utc).AddTicks(8277),
                            EndDate = "January 2023",
                            RoleName = "Freelance Virtual Assistant",
                            StartDate = "September 2020"
                        });
                });

            modelBuilder.Entity("VM_Server.Model.Projects", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageLink")
                        .HasColumnType("text");

                    b.Property<string>("ProjectLink")
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("vm_projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8436f29f-bd2d-4dad-9411-7377e62e688c"),
                            CreatedDateTime = new DateTime(2024, 11, 7, 16, 47, 0, 70, DateTimeKind.Utc).AddTicks(7888),
                            ImageLink = "https://res.cloudinary.com/dg1bym3ax/image/upload/v1730954820/vmdev/fcc_bi4o7r.png",
                            ProjectLink = "https://github.com/vmangahis/Four-Color-Conjecture-Game",
                            ProjectName = "Four Color Conjecture Game"
                        },
                        new
                        {
                            Id = new Guid("aeff3345-8bcf-4aa1-b9fe-772c86a8abd0"),
                            CreatedDateTime = new DateTime(2024, 11, 7, 16, 47, 0, 70, DateTimeKind.Utc).AddTicks(7902),
                            ImageLink = "https://res.cloudinary.com/dg1bym3ax/image/upload/v1730954822/vmdev/beowulf_tfac0o.png",
                            ProjectLink = "https://github.com/vmangahis/beowulf",
                            ProjectName = "Beowulf"
                        },
                        new
                        {
                            Id = new Guid("97d21240-7664-4e61-ac7c-6165b9bc3828"),
                            CreatedDateTime = new DateTime(2024, 11, 7, 16, 47, 0, 70, DateTimeKind.Utc).AddTicks(7906),
                            ImageLink = "https://res.cloudinary.com/dg1bym3ax/image/upload/v1730954820/vmdev/apt_jd51xf.png",
                            ProjectLink = "https://github.com/vmangahis/apartment-rental-system",
                            ProjectName = "Apartment Rental Management System"
                        },
                        new
                        {
                            Id = new Guid("aa7a7e72-cfc2-4c6f-8665-9411bff2bdf6"),
                            CreatedDateTime = new DateTime(2024, 11, 7, 16, 47, 0, 70, DateTimeKind.Utc).AddTicks(7910),
                            ImageLink = "https://res.cloudinary.com/dg1bym3ax/image/upload/v1730954839/vmdev/kai_gb2jzi.png",
                            ProjectLink = "https://github.com/vmangahis/Kai",
                            ProjectName = "Kai"
                        });
                });

            modelBuilder.Entity("VM_Server.Model.Skills", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SkillDescription")
                        .HasColumnType("text");

                    b.Property<string>("SkillIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("SkillName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("vm_skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f38508c1-df57-4885-852b-9aa0debff08f"),
                            CreatedDateTime = new DateTime(2024, 11, 7, 16, 47, 0, 70, DateTimeKind.Utc).AddTicks(8135),
                            SkillIdentifier = "msql_server",
                            SkillName = "Microsoft SQL Server"
                        },
                        new
                        {
                            Id = new Guid("ca03be6c-f67d-40fe-882f-9847fb9e2352"),
                            CreatedDateTime = new DateTime(2024, 11, 7, 16, 47, 0, 70, DateTimeKind.Utc).AddTicks(8139),
                            SkillIdentifier = "django",
                            SkillName = "Django"
                        },
                        new
                        {
                            Id = new Guid("af917738-b231-45d7-86b5-1a735617e6c4"),
                            CreatedDateTime = new DateTime(2024, 11, 7, 16, 47, 0, 70, DateTimeKind.Utc).AddTicks(8143),
                            SkillIdentifier = "postgresql",
                            SkillName = "PostgreSQL"
                        },
                        new
                        {
                            Id = new Guid("096e333d-81b0-47f4-847d-b64d225fb950"),
                            CreatedDateTime = new DateTime(2024, 11, 7, 16, 47, 0, 70, DateTimeKind.Utc).AddTicks(8146),
                            SkillIdentifier = "dotnet",
                            SkillName = ".NET Core"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
